export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const GET_ITEMS_REQUEST ="GET_ITEMS_REQUEST";
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
