export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST";
export const FEATURED_ITEMS_REQUEST = "FEATURED_ITEMS_REQUEST";
export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";